### ISSUE TITLE
i runn node . and it gives an error

### ISSUE THREAD

**Issue by BalteMD** [jiaabid/screen-sharing-app#1]

**Comment by Shahi-Paneer** [comment]
> Error: Cannot find module 'electron'
> 
> Require stack:
> 
> - C:\Users\Hoang Dung\Downloads\screen-sharing-app-master\client\app.js
> 
>     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
> 
>     at Module._load (node:internal/modules/cjs/loader:841:27)
> 
>     at Module.require (node:internal/modules/cjs/loader:1061:19)
> 
>     at require (node:internal/modules/cjs/helpers:103:18)
> 
>     at Object.<anonymous> (C:\Users\Hoang Dung\Downloads\screen-sharing-app-master\client\app.js:1:57)       
> 
>     at Module._compile (node:internal/modules/cjs/loader:1159:14)
> 
>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
> 
>     at Module.load (node:internal/modules/cjs/loader:1037:32)
> 
>     at Module._load (node:internal/modules/cjs/loader:878:12)
> 
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
> 
>   code: 'MODULE_NOT_FOUND',
> 
>   requireStack: [
> 
>     'C:\\Users\\Hoang Dung\\Downloads\\screen-sharing-app-master\\client\\app.js'
> 
>   ]
> 
> }
> 
> 
> 
> Node.js v18.12.0

Have you tried npm i ?

**Comment by Rathod-Tejas** [comment]
You have install electron-js  package and also you can install robots-js package but as per Requirement  
Follow this Document 
-- https://www.electron.build/cli.html
-- Win to install python 2.7 version and visual studio code 2017 download and Added the C++ Development package 
-- Package.json file last to added this Code 
 
"win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    } 

and then run the code : (npm run dist ) this Command to creating Build file 
If Any Error Setup then Contact me
